.\" Copyright (c) 2023
.\"    Los Alamos National Laboratory
.\"
.\" %%%LICENSE_START(GPLv3)
.\" See the file LICENSE in this distribution.
.\" %%%LICENSE_END
.\"
.\"
.TH FEMTOTIME 3 2023-05-12 "GNU" "Linux Programmer's Manual"
.SH NAME
The femtotime library
\- a simple library for femtotime resolution time calculations
.SH SYNOPSIS
.nf
.B #include <femtotime/GPSTime.hpp>
.PP
This is a placeholder until we provide a complete man page.
.SH DESCRIPTION
This is a placeholder until we provide a complete man page.
.SH SEE ALSO
.BR time (2),
.SH COLOPHON
This page is a placeholder.
.I man-pages
project.
A description of the project,
information about reporting bugs,
and the latest version of this page,
can be found at
\%https://NOTYET.DOMAIN/doc/man\-pages/.
